import test from 'node:test';
import assert from 'node:assert/strict';
import { PREMIUM_PUBLICATION_STYLES, PREMIUM_REPORT_ASSIGNMENTS, getPremiumPublicationCatalog, buildPremiumCover, composePremiumPublication, buildPremiumPublicationManifest } from '../src/premium-publications.js';

const governed={title:'National Youth Employment Intelligence',country:'Tanzania',sector:'Youth Employment',organization_name:'VoiceInsights Africa',findings:[{claim:'Skills mismatch is a priority constraint',evidence_id:'EV-1'}],evidence:[{evidence_id:'EV-1',claim:'Skills mismatch',response_id:'R-1',confidence_score:92,consent_status:'Granted',reviewer:'M&E'}],recommendations:[{decision:'Build employer-linked pathways',owner:'Programme Director',timeline:'0-90 days',priority:'High',monitoring_indicator:'Placement rate'}],methodology:{sample_design:'Stratified design',sample_size:1200,sampling_frame:'Frame',analysis_plan:'Plan'},limitations:['Synthetic demonstration evidence']};

test('phase2 exposes seven distinct premium publication styles',()=>{assert.equal(Object.keys(PREMIUM_PUBLICATION_STYLES).length,7);for(const k of ['government','donor','un','board','corporate','research','humanitarian']) assert.ok(PREMIUM_PUBLICATION_STYLES[k]);});
test('each premium style has a unique visual identity and substantive sections',()=>{const palettes=new Set();for(const s of Object.values(PREMIUM_PUBLICATION_STYLES)){palettes.add(JSON.stringify(s.palette));assert.ok(s.mandatory_sections.length>=9);assert.ok(s.visuals.length>=6);assert.ok(s.deliverables.length>=4);}assert.equal(palettes.size,7);});
test('all 16 flagship sample personalities map to a premium style',()=>{assert.equal(Object.keys(PREMIUM_REPORT_ASSIGNMENTS).length,16);for(const s of Object.values(PREMIUM_REPORT_ASSIGNMENTS))assert.ok(PREMIUM_PUBLICATION_STYLES[s]);});
test('premium cover adapts identity without fabricating report facts',()=>{const c=buildPremiumCover(governed,'government');assert.match(c.title,/Tanzania/);assert.match(c.title,/Youth Employment/);assert.ok(c.palette.primary);});
test('composer includes core intelligence, section evidence status and quality gate',()=>{const p=composePremiumPublication(governed,'donor');assert.equal(p.style_key,'donor');assert.ok(p.compiled_core);assert.ok(p.publication_quality_gate);assert.equal(p.sections.length,PREMIUM_PUBLICATION_STYLES.donor.mandatory_sections.length);assert.match(p.integrity_notice,/does not create evidence/);});
test('manifest exposes multi-format premium publication outputs',()=>{const m=buildPremiumPublicationManifest(governed,'board');assert.equal(m.style,'board');assert.ok(m.formats.includes('Print-ready PDF'));assert.ok(m.products.length>=4);});
test('catalog documents non-fabrication policy',()=>{const c=getPremiumPublicationCatalog();assert.equal(c.styles.length,7);assert.match(c.non_fabrication_policy,/Missing evidence/);});
