import test from 'node:test';import assert from 'node:assert/strict';
import {getPresentationPublishingCatalog,buildPublicationModel,evaluatePresentationQuality,buildCabinetMemo,buildPolicyBrief,buildDeck} from '../src/presentation-publishing.js';
const report={title:'National Human Development Intelligence',organization_name:'VoiceInsights Africa',executive_summary:'Decision-ready summary.',findings:[{text:'Youth employment is constrained.',evidence_ids:['E1']}],evidence:[{id:'E1',source:'Survey Q1',confidence_score:92}],recommendations:[{recommendation:'Prioritise skills-to-work transition.',owner:'Ministry',timeline:'0-90 days'}],methodology:{sample_design:'Stratified',sample_size:1200},limitations:['Demo evidence'],accessibility:true,brand_compliance:true};
test('catalog has seven international profiles and nine products',()=>{const c=getPresentationPublishingCatalog();assert.equal(c.profiles.length,7);assert.equal(c.products.length,9)});
test('publication model keeps distinct profile identity',()=>{const p=buildPublicationModel({report},'government','cabinet_memo');assert.equal(p.profile.key,'government');assert.equal(p.product.key,'cabinet_memo');assert.ok(p.cover.palette.primary)});
test('cabinet memo and policy brief have required sections',()=>{const m=buildCabinetMemo(report),b=buildPolicyBrief(report);assert.ok(m.decision_required);assert.ok(Array.isArray(m.evidence));assert.ok(b.issue);assert.ok(Array.isArray(b.citations))});
test('board and investor decks contain editable native slide schemas',()=>{for(const k of ['board_deck','investor_deck']){const d=buildDeck(report,k);assert.equal(d.native_editable_objects,true);assert.ok(d.slides.length>=8);assert.ok(d.slides.every(s=>s.editable&&s.content))}});
test('presentation gate blocks broken references and page overflow',()=>{const q=evaluatePresentationQuality({...report,references:[{broken:true}],page_overflow:true},'un','premium_pdf');assert.equal(q.status,'BLOCKED');assert.ok(q.blockers.includes('broken_references'));assert.ok(q.blockers.includes('page_overflow'))});
test('workspace and routes are wired',async()=>{const fs=await import('node:fs/promises');const index=await fs.readFile(new URL('../src/application.js',import.meta.url),'utf8');const html=await fs.readFile(new URL('../../site/app/presentation-publishing.html',import.meta.url),'utf8');for(const route of ['/api/reports/flagship/publishing/catalog','/api/reports/flagship/publishing/compose','/api/reports/flagship/publishing/quality-gate','/api/reports/flagship/publishing/export'])assert.ok(index.includes(route));assert.ok(html.includes('Generate & Download'))});
