import {test} from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path';
import {auditUiDocument,auditFrontendSecurity,auditWcag22,buildCsp,recordCspReport} from '../src/frontend-assurance.js';
import {discoverOidc,createPkce,exchangeAuthorizationCode,validateIdTokenClaims,providerActivationStatus,verifyScimBearer} from '../src/identity-live-validation.js';
import {guardTwilioWebhook} from '../src/twilio-security.js';
import {sha256Hex} from '../src/enterprise-identity-access.js';
const site=path.resolve('../site');
function htmlFiles(dir){const out=[];(function walk(p){for(const e of fs.readdirSync(p,{withFileTypes:true})){const f=path.join(p,e.name);e.isDirectory()?walk(f):/\.html$/i.test(e.name)&&out.push(f);}})(dir);return out;}
async function sign(url,params,token='token'){const payload=Object.keys(params).sort().reduce((s,k)=>s+k+params[k],url);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(token),{name:'HMAC',hash:'SHA-1'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload));return btoa(String.fromCharCode(...new Uint8Array(sig)));}
test('UI assurance scans every production HTML document and returns actionable records',()=>{const files=htmlFiles(site);assert.ok(files.length>20);const reports=files.map(f=>auditUiDocument(fs.readFileSync(f,'utf8'),{path:path.relative(site,f)}));assert.equal(reports.length,files.length);assert.ok(reports.every(r=>Array.isArray(r.issues)));});
test('frontend security audit detects real executable sinks rather than placeholder strings',()=>{const bad='<button onclick="x()">X</button><script>eval(x)</script><div id=x></div><script>x.innerHTML=y</script>';const r=auditFrontendSecurity(bad);assert.deepEqual(new Set(r.issues.map(x=>x.code)),new Set(['INLINE_EVENT_HANDLER','INLINE_SCRIPT','UNSAFE_HTML_SINK','DYNAMIC_CODE_EXECUTION']));assert.equal(r.strict_csp_ready,false);});
test('WCAG audit validates names, landmarks, headings, images and tables',()=>{const bad='<html><body><img src=x><input id=q><table><tr><td>x</td></tr></table></body></html>';const codes=auditWcag22(bad).issues.map(x=>x.code);for(const c of ['LANG_MISSING','MAIN_LANDMARK_MISSING','SKIP_LINK_MISSING','H1_MISSING','IMAGE_ALT_MISSING','INPUT_NAME_MISSING','TABLE_HEADERS_MISSING'])assert.ok(codes.includes(c));});
test('CSP remains report-only until inline dependencies are removed',()=>{const c=buildCsp({reportOnly:true});assert.equal(c.header,'Content-Security-Policy-Report-Only');assert.equal(c.enforcement_ready,false);assert.match(c.value,/report-uri/);});
test('CSP violation endpoint persists a real browser report and fails closed on storage outage',async()=>{let saved;const env={DB:{prepare(){return{bind(...a){saved=a;return this},async run(){return{meta:{changes:1}}}}}}};const request=new Request('https://x/api/security/csp-report',{method:'POST',headers:{'content-type':'application/csp-report'},body:JSON.stringify({'csp-report':{'document-uri':'https://x/app','violated-directive':'script-src','blocked-uri':'inline'}})});assert.equal((await recordCspReport(request,env)).status,204);assert.equal(saved[2],'script-src');const fail={DB:{prepare(){return{bind(){return this},async run(){throw new Error('down')}}}}};const request2=new Request('https://x/api/security/csp-report',{method:'POST',body:JSON.stringify({'csp-report':{'violated-directive':'style-src'}})});assert.equal((await recordCspReport(request2,fail)).status,503);});
test('OIDC live verification performs discovery, PKCE and token exchange',async()=>{const issuer='https://id.example';const calls=[];const fetchFn=async(url,init={})=>{calls.push([url,init]);if(url.endsWith('openid-configuration'))return new Response(JSON.stringify({issuer,authorization_endpoint:issuer+'/authorize',token_endpoint:issuer+'/token',jwks_uri:issuer+'/jwks'}),{status:200});return new Response(JSON.stringify({id_token:'header.payload.sig',access_token:'a'}),{status:200});};const discovery=await discoverOidc(issuer,fetchFn);const pkce=await createPkce();assert.ok(pkce.verifier.length>30&&pkce.challenge.length>30);const token=await exchangeAuthorizationCode({discovery,client_id:'c',code:'code',redirect_uri:'https://app/callback',code_verifier:pkce.verifier,fetchFn});assert.equal(token.access_token,'a');assert.equal(calls.length,2);});
test('OIDC claims and activation never become active without complete live evidence',()=>{assert.equal(validateIdTokenClaims({iss:'i',aud:'c',nonce:'n',exp:9999999999},{issuer:'i',audience:'c',nonce:'n'}).ok,true);assert.equal(validateIdTokenClaims({iss:'wrong',aud:'c',exp:1},{issuer:'i',audience:'c'}).ok,false);assert.equal(providerActivationStatus({discovery_verified_at:'now'}).status,'REQUIRES_LIVE_VALIDATION');assert.equal(providerActivationStatus({discovery_verified_at:'1',token_exchange_verified_at:'1',jwks_verified_at:'1',login_verified_at:'1',logout_verified_at:'1'}).status,'ACTIVE');});
test('SCIM bearer comparison uses hashed token and rejects missing or wrong tokens',async()=>{const expected=await sha256Hex('secret');const ok=await verifyScimBearer(new Request('https://x',{headers:{Authorization:'Bearer secret'}}),expected,sha256Hex);const bad=await verifyScimBearer(new Request('https://x',{headers:{Authorization:'Bearer wrong'}}),expected,sha256Hex);assert.equal(ok,true);assert.equal(bad,false);});
test('Twilio signed request returns 503 and is never processed when replay registry is unavailable',async()=>{const url='https://api.example/api/sms/webhook';const params={From:'+255700000001',Body:'hello',MessageSid:'SMFAIL'};const signature=await sign(url,params);const req=new Request(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Twilio-Signature':signature},body:new URLSearchParams(params)});const env={TWILIO_AUTH_TOKEN:'token',DB:{prepare(sql){return{bind(){return this},async run(){if(/twilio_event_registry/.test(sql))throw new Error('D1 down');return{meta:{changes:1}}}}}}};const result=await guardTwilioWebhook(req,env);assert.equal(result.ok,false);assert.equal(result.response.status,503);assert.equal(result.response.headers.get('Retry-After'),'30');});
