import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {buildVinReadiness,validateVinConsent,canActivateVin,aggregatePrivacySafeSnapshots,buildVinWorkspace,buildCollaborationOpportunity,VIN_PRODUCT_NAME} from '../src/voiceinsights-intelligence-network.js';
test('VIN product name has no customer-facing version number',()=>assert.equal(VIN_PRODUCT_NAME,'VoiceInsights Intelligence Network™ (VIN™)'));
test('network stays preparing until minimums are reached',()=>{const r=buildVinReadiness({organizations:5,countries:1,regions:1,opted_in_organizations:2,benchmark_cloud_ready:true,knowledge_cloud_ready:true,security_ready:true,compliance_ready:true});assert.equal(r.ready_for_activation,false);assert.equal(r.network_status,'PREPARING_NETWORK')});
test('network becomes activation-ready only when all controls pass',()=>{const r=buildVinReadiness({organizations:20,countries:5,regions:2,opted_in_organizations:15,benchmark_cloud_ready:true,knowledge_cloud_ready:true,security_ready:true,compliance_ready:true});assert.equal(r.ready_for_activation,true);assert.equal(canActivateVin({role:'super_admin',readiness:r,founder_confirmed:true}).ok,true)});
test('organization opt-in enforces dependency rules',()=>{assert.equal(validateVinConsent({public_statistics:true}).ok,false);assert.equal(validateVinConsent({anonymous_benchmarking:true,africa_intelligence:true,public_statistics:true}).ok,true)});
test('privacy aggregation suppresses peer groups smaller than five',()=>{const rows=[1,2,3,4].map((x,i)=>({organization_id:'o'+i,opted_in:1,country:'TZ',region:'EA',sector:'health',metric_key:'response_rate',metric_value:70+x}));assert.equal(aggregatePrivacySafeSnapshots(rows).length,0);rows.push({organization_id:'o5',opted_in:1,country:'TZ',region:'EA',sector:'health',metric_key:'response_rate',metric_value:80});assert.equal(aggregatePrivacySafeSnapshots(rows).length,1)});
test('VIN workspace contains registry governance intelligence and collaboration modules',()=>{const w=buildVinWorkspace({organizations:0,opted_in_organizations:0,countries:0,regions:0,snapshots:[]});for(const k of ['network_registry','opt_in_governance','country_intelligence','regional_intelligence','sdg_intelligence','research_collaboration'])assert.ok(w.modules.some(m=>m.key===k))});
test('collaboration opportunities require core fields',()=>{assert.equal(buildCollaborationOpportunity({}).ok,false);assert.equal(buildCollaborationOpportunity({title:'Baseline partner',country:'Tanzania',sector:'health',opportunity_type:'research_partner'}).ok,true)});
test('routes schema and user-facing pages are wired',()=>{const index=fs.readFileSync(new URL('../src/application.js',import.meta.url),'utf8');for(const p of ['/api/intelligence-network/workspace','/api/intelligence-network/consent','/api/intelligence-network/activate','/api/intelligence-network/collaboration'])assert.ok(index.includes(p));const schema=fs.readFileSync(new URL('../schema.sql',import.meta.url),'utf8');assert.ok(schema.includes('vin_network_registry'));for(const p of ['../../site/app/intelligence-network.html','../../site/app/intelligence-network-governance.html','../../site/admin/intelligence-network-activation.html','../../site/app/research-collaboration-hub.html'])assert.ok(fs.existsSync(new URL(p,import.meta.url)))});
