import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const indexSource = fs.readFileSync(new URL('../src/application.js', import.meta.url), 'utf8');
const viewerSource = fs.readFileSync(new URL('../../site/sample-report-viewer.html', import.meta.url), 'utf8');
const librarySource = fs.readFileSync(new URL('../../site/sample-reports.html', import.meta.url), 'utf8');
const showcaseSource = fs.readFileSync(new URL('../src/vrds-showcase-experience.js', import.meta.url), 'utf8');
const showcaseCss = fs.readFileSync(new URL('../../site/assets/css/vrds-showcase.css', import.meta.url), 'utf8');

test('public track-download is hard-filtered to published demo reports', () => {
  assert.match(indexSource, /track-download/);
  assert.match(indexSource, /demo_downloads = demo_downloads \+ 1 WHERE id = \? AND is_demo = 1 AND status = 'published'/);
});

test('public viewer uses honest export labels for preview and print flows', () => {
  assert.match(viewerSource, /Print-ready report/);
  assert.match(viewerSource, /Presentation-ready board outline/);
  assert.match(viewerSource, /Export Previews/);
  assert.match(viewerSource, /Export preview prepared from the public demonstration report evidence package/);
  assert.doesNotMatch(viewerSource, />Sample PDF</);
  assert.doesNotMatch(viewerSource, />Board PPT</);
});

test('public sample library download actions are labelled as previews, not production-grade exports', () => {
  assert.match(librarySource, /Download Donor Impact Preview/);
  assert.match(librarySource, /Download Policy Brief Preview/);
  assert.match(librarySource, /Download Infographic Preview/);
  assert.match(librarySource, /Download Board Outline Preview/);
  assert.match(librarySource, /Export Preview/);
});

test('public fallback wording is professional and avoids internal showcase labels', () => {
  assert.match(viewerSource, /This report experience is temporarily unavailable\. Please return to the sample library or request a demo\./);
  assert.doesNotMatch(viewerSource, /The VRDS showcase package could not be loaded/);
  assert.doesNotMatch(viewerSource, /<h2>VRDS Showcase Experience<\/h2>/);
  assert.doesNotMatch(viewerSource, /Structured assistant actions use existing report intelligence only/);
});

test('public wording sanitizer removes unsafe public phrases from export text', () => {
  assert.match(viewerSource, /function sanitizePublicExportText/);
  assert.match(viewerSource, /Not enough data/);
  assert.match(viewerSource, /Insufficient verified evidence available/);
  assert.match(viewerSource, /generated by system/);
  assert.match(viewerSource, /prepared by the report engine/);
  assert.match(viewerSource, /raw JSON/);
  assert.match(viewerSource, /structured data/);
  assert.match(viewerSource, /undefined/);
  assert.match(viewerSource, /Not reported/);
});

test('infographic sections expose publication-style structure and print-safe layout hooks', () => {
  assert.match(showcaseSource, /executive_headline/);
  assert.match(showcaseSource, /interpretation/);
  assert.match(showcaseSource, /decision_implication/);
  assert.match(showcaseCss, /publication pages/);
  assert.match(showcaseCss, /grid-template-columns:minmax/);
  assert.match(showcaseCss, /@media print/);
});
