import test from 'node:test';import assert from 'node:assert/strict';
import {validateQueueJob,computeWorkloadPlan,evaluateLoadTest,evaluateFailover,evaluateBackupRestore,buildCloudIntelligenceReadiness,buildScaleIntelligenceWorkspace} from '../src/scale-cloud-intelligence-workstream4.js';
import fs from 'node:fs';
test('queue validation enforces idempotency and campaign context',()=>{assert.equal(validateQueueJob({queue_type:'phone',organization_id:'o'}).ok,false);assert.equal(validateQueueJob({queue_type:'phone',organization_id:'o',campaign_id:'c',idempotency_key:'x'}).ok,true)});
test('workload plan identifies critical queues',()=>{const p=computeWorkloadPlan({queue_depths:{sms:40},worker_capacity:{sms:20}});assert.equal(p.critical[0].type,'sms')});
test('load test requires international acceptance thresholds',()=>{const r=evaluateLoadTest({virtual_users:100,duration_minutes:30,requests_total:10000,success_rate_pct:99.9,p95_latency_ms:500,error_rate_pct:.1,data_loss_count:0,duplicate_job_count:0,campaigns_per_day_proven:100});assert.equal(r.status,'PASS');assert.equal(r.capacity_claim,100)});
test('failover and restore require evidence and RTO RPO compliance',()=>{assert.equal(evaluateFailover({trigger:'d1',secondary_path_used:true,recovery_time_minutes:10,rto_minutes:60,data_loss_minutes:0,rpo_minutes:15,rollback_verified:true,evidence_reference:'e'}).status,'PASS');assert.equal(evaluateBackupRestore({backup_reference:'b',restore_completed:true,integrity_verified:true,row_counts_reconciled:true,application_smoke_test:true,restore_minutes:20,rto_minutes:120,evidence_reference:'e'}).status,'PASS')});
test('readiness does not claim 95 without live operational evidence',()=>{const r=buildCloudIntelligenceReadiness({production_queues:true,workload_balancing:true,monitoring:true,disaster_recovery:true,knowledge_cloud:true,marketplace:true,benchmark_cloud:true,api_platform:true,customer_success:true,training:true,support_sla:true,renewal:true,expansion:true,vin:true});assert.ok(r.verified_readiness_pct<95)});
test('workspace includes all requested cloud and customer success modules',()=>{const w=buildScaleIntelligenceWorkspace({});assert.ok(w.cloud_modules.includes('VoiceInsights Intelligence Network™ (VIN™)'));assert.equal(w.acceptance_required.length,3)});
// Enterprise Market Validation Release, Part A: publicationScoreText() was
// confirmed dead code (defined, exported to window, never called anywhere
// in this file) that read the now-removed report.quality_score field —
// removed rather than left as broken dead code referencing a field that no
// longer exists on the public catalog response.
test('report library does not reference removed score fields or premium_score',()=>{const s=fs.readFileSync(new URL('../../site/sample-reports.html',import.meta.url),'utf8');assert.doesNotMatch(s,/p\.premium_score/);assert.doesNotMatch(s,/publicationScoreText/);assert.doesNotMatch(s,/report\.quality_score\b/)});
test('routes migration and dashboard are wired',()=>{const idx=fs.readFileSync(new URL('../src/application.js',import.meta.url),'utf8');assert.match(idx,/\/api\/scale-intelligence\/workspace/);assert.match(idx,/operational_acceptance_runs_ws4/);assert.ok(fs.existsSync(new URL('../migrations/025_scale_cloud_intelligence_workstream4.sql',import.meta.url)));assert.ok(fs.existsSync(new URL('../../site/admin/scale-cloud-intelligence-operations.html',import.meta.url)))});
